#pragma once
// Generated by tools/generate-phone-text-abi.py from Microsoft SDK ABI.
struct PhoneCoreTextRange { INT32 StartCaretPosition; INT32 EndCaretPosition; };
struct PhoneCoreTextEditContext;
struct PhoneCoreTextServicesManager;
struct PhoneCoreTextServicesManagerStatics;
struct PhoneCoreTextTextRequest;
struct PhoneCoreTextTextRequestedEventArgs;
struct PhoneCoreTextSelectionRequest;
struct PhoneCoreTextSelectionRequestedEventArgs;
struct PhoneCoreTextLayoutBounds;
struct PhoneCoreTextLayoutRequest;
struct PhoneCoreTextLayoutRequestedEventArgs;
struct PhoneCoreTextTextUpdatingEventArgs;
struct PhoneCoreTextSelectionUpdatingEventArgs;
struct __declspec(uuid("bf6608af-4041-47c3-b263-a918eb5eaef2")) PhoneCoreTextEditContext : IInspectable {
virtual HRESULT STDMETHODCALLTYPE get_Name( HSTRING* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE put_Name( HSTRING value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_InputScope( INT32* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE put_InputScope( INT32 value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_IsReadOnly( boolean* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE put_IsReadOnly( boolean value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_InputPaneDisplayPolicy( INT32* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE put_InputPaneDisplayPolicy( INT32 value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE add_TextRequested( IUnknown* handler, EventRegistrationToken* cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE remove_TextRequested( EventRegistrationToken cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE add_SelectionRequested( IUnknown* handler, EventRegistrationToken* cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE remove_SelectionRequested( EventRegistrationToken cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE add_LayoutRequested( IUnknown* handler, EventRegistrationToken* cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE remove_LayoutRequested( EventRegistrationToken cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE add_TextUpdating( IUnknown* handler, EventRegistrationToken* cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE remove_TextUpdating( EventRegistrationToken cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE add_SelectionUpdating( IUnknown* handler, EventRegistrationToken* cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE remove_SelectionUpdating( EventRegistrationToken cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE add_FormatUpdating( IUnknown* handler, EventRegistrationToken* cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE remove_FormatUpdating( EventRegistrationToken cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE add_CompositionStarted( IUnknown* handler, EventRegistrationToken* cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE remove_CompositionStarted( EventRegistrationToken cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE add_CompositionCompleted( IUnknown* handler, EventRegistrationToken* cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE remove_CompositionCompleted( EventRegistrationToken cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE add_FocusRemoved( IUnknown* handler, EventRegistrationToken* cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE remove_FocusRemoved( EventRegistrationToken cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE NotifyFocusEnter(void) = 0;
 virtual HRESULT STDMETHODCALLTYPE NotifyFocusLeave(void) = 0;
 virtual HRESULT STDMETHODCALLTYPE NotifyTextChanged( PhoneCoreTextRange modifiedRange, INT32 newLength, PhoneCoreTextRange newSelection ) = 0;
 virtual HRESULT STDMETHODCALLTYPE NotifySelectionChanged( PhoneCoreTextRange selection ) = 0;
 virtual HRESULT STDMETHODCALLTYPE NotifyLayoutChanged(void) = 0;

};
__CRT_UUID_DECL(PhoneCoreTextEditContext,0xbf6608af,0x4041,0x47c3,0xb2,0x63,0xa9,0x18,0xeb,0x5e,0xae,0xf2)
struct __declspec(uuid("c2507d83-6e0a-4a8a-bdf8-1948874854ba")) PhoneCoreTextServicesManager : IInspectable {
virtual HRESULT STDMETHODCALLTYPE get_InputLanguage( IInspectable** value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE add_InputLanguageChanged( IUnknown* handler, EventRegistrationToken* cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE remove_InputLanguageChanged( EventRegistrationToken cookie ) = 0;
 virtual HRESULT STDMETHODCALLTYPE CreateEditContext( PhoneCoreTextEditContext** value ) = 0;

};
__CRT_UUID_DECL(PhoneCoreTextServicesManager,0xc2507d83,0x6e0a,0x4a8a,0xbd,0xf8,0x19,0x48,0x87,0x48,0x54,0xba)
struct __declspec(uuid("1520a388-e2cf-4d65-aeb9-b32d86fe39b9")) PhoneCoreTextServicesManagerStatics : IInspectable {
virtual HRESULT STDMETHODCALLTYPE GetForCurrentView( PhoneCoreTextServicesManager** value ) = 0;

};
__CRT_UUID_DECL(PhoneCoreTextServicesManagerStatics,0x1520a388,0xe2cf,0x4d65,0xae,0xb9,0xb3,0x2d,0x86,0xfe,0x39,0xb9)
struct __declspec(uuid("50d950a9-f51e-4cc1-8ca1-e6346d1a61be")) PhoneCoreTextTextRequest : IInspectable {
virtual HRESULT STDMETHODCALLTYPE get_Range( PhoneCoreTextRange* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_Text( HSTRING* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE put_Text( HSTRING value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_IsCanceled( boolean* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE GetDeferral( IInspectable** value ) = 0;

};
__CRT_UUID_DECL(PhoneCoreTextTextRequest,0x50d950a9,0xf51e,0x4cc1,0x8c,0xa1,0xe6,0x34,0x6d,0x1a,0x61,0xbe)
struct __declspec(uuid("f096a2d0-41c6-4c02-8b1a-d953b00cabb3")) PhoneCoreTextTextRequestedEventArgs : IInspectable {
virtual HRESULT STDMETHODCALLTYPE get_Request( PhoneCoreTextTextRequest** value ) = 0;

};
__CRT_UUID_DECL(PhoneCoreTextTextRequestedEventArgs,0xf096a2d0,0x41c6,0x4c02,0x8b,0x1a,0xd9,0x53,0xb0,0x0c,0xab,0xb3)
struct __declspec(uuid("f0a70403-208b-4301-883c-74ca7485fd8d")) PhoneCoreTextSelectionRequest : IInspectable {
virtual HRESULT STDMETHODCALLTYPE get_Selection( PhoneCoreTextRange* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE put_Selection( PhoneCoreTextRange value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_IsCanceled( boolean* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE GetDeferral( IInspectable** value ) = 0;

};
__CRT_UUID_DECL(PhoneCoreTextSelectionRequest,0xf0a70403,0x208b,0x4301,0x88,0x3c,0x74,0xca,0x74,0x85,0xfd,0x8d)
struct __declspec(uuid("13c6682b-f614-421a-8f4b-9ec8a5a37fcd")) PhoneCoreTextSelectionRequestedEventArgs : IInspectable {
virtual HRESULT STDMETHODCALLTYPE get_Request( PhoneCoreTextSelectionRequest** value ) = 0;

};
__CRT_UUID_DECL(PhoneCoreTextSelectionRequestedEventArgs,0x13c6682b,0xf614,0x421a,0x8f,0x4b,0x9e,0xc8,0xa5,0xa3,0x7f,0xcd)
struct __declspec(uuid("e972c974-4436-4917-80d0-a525e4ca6780")) PhoneCoreTextLayoutBounds : IInspectable {
virtual HRESULT STDMETHODCALLTYPE get_TextBounds( Rect* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE put_TextBounds( Rect value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_ControlBounds( Rect* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE put_ControlBounds( Rect value ) = 0;

};
__CRT_UUID_DECL(PhoneCoreTextLayoutBounds,0xe972c974,0x4436,0x4917,0x80,0xd0,0xa5,0x25,0xe4,0xca,0x67,0x80)
struct __declspec(uuid("2555a8cc-51fd-4f03-98bf-ac78174d68e0")) PhoneCoreTextLayoutRequest : IInspectable {
virtual HRESULT STDMETHODCALLTYPE get_Range( PhoneCoreTextRange* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_LayoutBounds( PhoneCoreTextLayoutBounds** value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_IsCanceled( boolean* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE GetDeferral( IInspectable** value ) = 0;

};
__CRT_UUID_DECL(PhoneCoreTextLayoutRequest,0x2555a8cc,0x51fd,0x4f03,0x98,0xbf,0xac,0x78,0x17,0x4d,0x68,0xe0)
struct __declspec(uuid("b1dc6ae0-9a7b-4e9e-a566-4a6b5f8ad676")) PhoneCoreTextLayoutRequestedEventArgs : IInspectable {
virtual HRESULT STDMETHODCALLTYPE get_Request( PhoneCoreTextLayoutRequest** value ) = 0;

};
__CRT_UUID_DECL(PhoneCoreTextLayoutRequestedEventArgs,0xb1dc6ae0,0x9a7b,0x4e9e,0xa5,0x66,0x4a,0x6b,0x5f,0x8a,0xd6,0x76)
struct __declspec(uuid("eea7918d-cc2b-4f03-8ff6-02fd217db450")) PhoneCoreTextTextUpdatingEventArgs : IInspectable {
virtual HRESULT STDMETHODCALLTYPE get_Range( PhoneCoreTextRange* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_Text( HSTRING* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_NewSelection( PhoneCoreTextRange* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_InputLanguage( IInspectable** value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_Result( INT32* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE put_Result( INT32 value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_IsCanceled( boolean* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE GetDeferral( IInspectable** value ) = 0;

};
__CRT_UUID_DECL(PhoneCoreTextTextUpdatingEventArgs,0xeea7918d,0xcc2b,0x4f03,0x8f,0xf6,0x02,0xfd,0x21,0x7d,0xb4,0x50)
struct __declspec(uuid("d445839f-fe7f-4bd5-8a26-0922c1b3e639")) PhoneCoreTextSelectionUpdatingEventArgs : IInspectable {
virtual HRESULT STDMETHODCALLTYPE get_Selection( PhoneCoreTextRange* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_Result( INT32* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE put_Result( INT32 value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE get_IsCanceled( boolean* value ) = 0;
 virtual HRESULT STDMETHODCALLTYPE GetDeferral( IInspectable** value ) = 0;

};
__CRT_UUID_DECL(PhoneCoreTextSelectionUpdatingEventArgs,0xd445839f,0xfe7f,0x4bd5,0x8a,0x26,0x09,0x22,0xc1,0xb3,0xe6,0x39)
struct __declspec(uuid("ef53b467-c472-5b59-a827-38adc3a9d326")) PhoneCoreTextFocusRemovedHandler : IUnknown {
virtual HRESULT STDMETHODCALLTYPE Invoke(PhoneCoreTextEditContext*,IInspectable*)=0;
};
__CRT_UUID_DECL(PhoneCoreTextFocusRemovedHandler,0xef53b467,0xc472,0x5b59,0xa8,0x27,0x38,0xad,0xc3,0xa9,0xd3,0x26)
struct __declspec(uuid("a2d7059e-68ed-5260-8d8e-1dcf3d25d663")) PhoneCoreTextCompositionCompletedEventArgsHandler : IUnknown {
virtual HRESULT STDMETHODCALLTYPE Invoke(PhoneCoreTextEditContext*,IInspectable*)=0;
};
__CRT_UUID_DECL(PhoneCoreTextCompositionCompletedEventArgsHandler,0xa2d7059e,0x68ed,0x5260,0x8d,0x8e,0x1d,0xcf,0x3d,0x25,0xd6,0x63)
struct __declspec(uuid("e671d625-5b59-57e6-a92e-40009507853a")) PhoneCoreTextCompositionStartedEventArgsHandler : IUnknown {
virtual HRESULT STDMETHODCALLTYPE Invoke(PhoneCoreTextEditContext*,IInspectable*)=0;
};
__CRT_UUID_DECL(PhoneCoreTextCompositionStartedEventArgsHandler,0xe671d625,0x5b59,0x57e6,0xa9,0x2e,0x40,0x00,0x95,0x07,0x85,0x3a)
struct __declspec(uuid("3e4ef599-4cc2-5248-bf2d-13f17613b0a6")) PhoneCoreTextFormatUpdatingEventArgsHandler : IUnknown {
virtual HRESULT STDMETHODCALLTYPE Invoke(PhoneCoreTextEditContext*,IInspectable*)=0;
};
__CRT_UUID_DECL(PhoneCoreTextFormatUpdatingEventArgsHandler,0x3e4ef599,0x4cc2,0x5248,0xbf,0x2d,0x13,0xf1,0x76,0x13,0xb0,0xa6)
struct __declspec(uuid("1a5f5596-561c-57f6-a4ff-cb85013c6544")) PhoneCoreTextLayoutRequestedEventArgsHandler : IUnknown {
virtual HRESULT STDMETHODCALLTYPE Invoke(PhoneCoreTextEditContext*,PhoneCoreTextLayoutRequestedEventArgs*)=0;
};
__CRT_UUID_DECL(PhoneCoreTextLayoutRequestedEventArgsHandler,0x1a5f5596,0x561c,0x57f6,0xa4,0xff,0xcb,0x85,0x01,0x3c,0x65,0x44)
struct __declspec(uuid("882e51e1-f4a3-57e5-9392-6a8c38579181")) PhoneCoreTextSelectionRequestedEventArgsHandler : IUnknown {
virtual HRESULT STDMETHODCALLTYPE Invoke(PhoneCoreTextEditContext*,PhoneCoreTextSelectionRequestedEventArgs*)=0;
};
__CRT_UUID_DECL(PhoneCoreTextSelectionRequestedEventArgsHandler,0x882e51e1,0xf4a3,0x57e5,0x93,0x92,0x6a,0x8c,0x38,0x57,0x91,0x81)
struct __declspec(uuid("6b140a40-d461-555a-b6eb-5dbb8e2101e5")) PhoneCoreTextSelectionUpdatingEventArgsHandler : IUnknown {
virtual HRESULT STDMETHODCALLTYPE Invoke(PhoneCoreTextEditContext*,PhoneCoreTextSelectionUpdatingEventArgs*)=0;
};
__CRT_UUID_DECL(PhoneCoreTextSelectionUpdatingEventArgsHandler,0x6b140a40,0xd461,0x555a,0xb6,0xeb,0x5d,0xbb,0x8e,0x21,0x01,0xe5)
struct __declspec(uuid("c7e08176-4134-50b7-bc73-729e9f9ad22a")) PhoneCoreTextTextRequestedEventArgsHandler : IUnknown {
virtual HRESULT STDMETHODCALLTYPE Invoke(PhoneCoreTextEditContext*,PhoneCoreTextTextRequestedEventArgs*)=0;
};
__CRT_UUID_DECL(PhoneCoreTextTextRequestedEventArgsHandler,0xc7e08176,0x4134,0x50b7,0xbc,0x73,0x72,0x9e,0x9f,0x9a,0xd2,0x2a)
struct __declspec(uuid("fd896a84-df7c-50d5-9167-58f616bddb6e")) PhoneCoreTextTextUpdatingEventArgsHandler : IUnknown {
virtual HRESULT STDMETHODCALLTYPE Invoke(PhoneCoreTextEditContext*,PhoneCoreTextTextUpdatingEventArgs*)=0;
};
__CRT_UUID_DECL(PhoneCoreTextTextUpdatingEventArgsHandler,0xfd896a84,0xdf7c,0x50d5,0x91,0x67,0x58,0xf6,0x16,0xbd,0xdb,0x6e)
