# The approved file_selector_windows 0.9.3+3 correction is a package bug that
# also reproduces with MSVC. Keep it separate from compiler compatibility and
# apply only to a checksum-pinned build-output copy of this original source.
function(_flutter_arm32_file_selector_source target)
  if(NOT TARGET "${target}")
    return()
  endif()
  get_target_property(_sources "${target}" SOURCES)
  get_target_property(_source_directory "${target}" SOURCE_DIR)
  set(_updated)
  foreach(_source IN LISTS _sources)
    if(_source MATCHES "(^|/)file_selector_plugin\\.cpp$")
      get_filename_component(_original "${_source}" ABSOLUTE BASE_DIR "${_source_directory}")
      file(SHA256 "${_original}" _checksum)
      if(_checksum STREQUAL "589d5c5a60237a3773477e4c6034f9343a48b1473bc86ea7ea74dc931ca2430f")
        file(READ "${_original}" _contents)
        string(REPLACE "#include <cassert>" "#include <cassert>\n#include <cstdint>" _contents "${_contents}")
        string(REPLACE "EncodableValue(dialog.last_result())"
          "EncodableValue(static_cast<int64_t>(dialog.last_result()))" _contents "${_contents}")
        set(_generated "${CMAKE_BINARY_DIR}/sdk-native/file_selector_windows/file_selector_plugin.cpp")
        file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/sdk-native/file_selector_windows")
        file(WRITE "${_generated}" "${_contents}")
        get_filename_component(_original_directory "${_original}" DIRECTORY)
        target_include_directories("${target}" PRIVATE "${_original_directory}")
        set(_source "${_generated}")
      endif()
    endif()
    list(APPEND _updated "${_source}")
  endforeach()
  set_property(TARGET "${target}" PROPERTY SOURCES "${_updated}")
endfunction()

# The original Windows runner compares signed int with unsigned size_type.
# MSVC also diagnoses this on 32-bit targets. Preserve the existing conversion
# semantics with one explicit cast in a checksum-pinned build-output copy.
function(_flutter_arm32_runner_source target)
  if(NOT TARGET "${target}")
    return()
  endif()
  get_target_property(_sources "${target}" SOURCES)
  get_target_property(_source_directory "${target}" SOURCE_DIR)
  set(_updated)
  foreach(_source IN LISTS _sources)
    if(_source MATCHES "(^|/)utils\\.cpp$")
      get_filename_component(_original "${_source}" ABSOLUTE BASE_DIR "${_source_directory}")
      file(SHA256 "${_original}" _checksum)
      if(_checksum STREQUAL "cd9cfd4646e2df3f23c0b0825999ed36b32f5a68c1e671883c63ccc1acb17d98")
        file(READ "${_original}" _contents)
        string(REPLACE "target_length > utf8_string.max_size()"
          "static_cast<std::string::size_type>(target_length) > utf8_string.max_size()"
          _contents "${_contents}")
        set(_generated "${CMAKE_BINARY_DIR}/sdk-native/runner/utils.cpp")
        file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/sdk-native/runner")
        file(WRITE "${_generated}" "${_contents}")
        get_filename_component(_original_directory "${_original}" DIRECTORY)
        target_include_directories("${target}" PRIVATE "${_original_directory}")
        set(_source "${_generated}")
      endif()
    endif()
    list(APPEND _updated "${_source}")
  endforeach()
  set_property(TARGET "${target}" PROPERTY SOURCES "${_updated}")
endfunction()

function(_flutter_arm32_native_package_compatibility)
  if(DEFINED BINARY_NAME)
    _flutter_arm32_runner_source("${BINARY_NAME}")
  endif()
  _flutter_arm32_file_selector_source(file_selector_windows_plugin)
  _flutter_arm32_file_selector_source(file_selector_windows_test)
endfunction()
